# Generated by Django 4.1 on 2022-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
            ],
        ),
    ]
